"""Frozen product contract. Changing this file is a breaking release."""

from __future__ import annotations

CONTRACT = {
    "api": "1.3.0",
    "player": "1.3.0",
    "ir": "1",
    "facade": "ux_motion",
    "op.play": "transition.play",
    "op.cancel": "transition.cancel",
    "op.rewind": "transition.rewind",
    "laws": (
        "Speak the intent: send.play / send.update / send.rewind.",
        "JSON is the shared language. No Python objects on the wire.",
        "Unknown fields are ignored. Keys are never reused.",
        "A new v is the only legal break. Additive fields only inside v1.",
        "Server authors composition. Client owns physical presence and measurement.",
        "Presence is per-target, never a single global tree.",
        "Nested groups are not flattened.",
        "wait partitions direct tracks; nested nodes run as their own units.",
        "as_update never drops a track silently.",
        "share is identity continuity; client measures, server only names.",
        "bind turns a plan into a 0..1 tape driven by scroll or drag.",
        "score holds exit presence across HTTP Results until the next cue.",
        "layout is stay until measurement is requested via share.",
        "engine=view uses View Transitions when present; engine=spring uses physics.",
        "Recipe names do what they say.",
        "Duration is capped at 120s.",
        "The reference player is the schedule contract.",
        "Reduced motion may swap an entire alternate tree, not only shorten ms.",
        "transition.* rides a Channel Result; MotionChannel plays them after authority morph.",
    ),
    "kinds": (
        "plan",
        "phase",
        "group",
        "track",
        "stagger",
        "share",
        "bind",
        "score",
        "cue",
    ),
    "modes": ("parallel", "sequence", "wait"),
    "roles": ("exit", "enter", "stay", "layout"),
    "after": ("keep", "remove", "hide"),
    "engines": ("presence", "view", "spring"),
    "bind_inputs": ("scroll", "drag", "progress"),
}
